sudo: false
env:
  global:
    - GH_REPO="makotot/construct"
    - GIT_COMMITTER_NAME=makotot
    - GIT_COMMITTER_EMAIL=makoto.ttn@gmail.com
    - GIT_AUTHOR_NAME=makotot
    - GIT_AUTHOR_EMAIL=makoto.ttn@gmail.com
    - secure: TKyFaC2ypIjHpmZXIS1pGXdqAHqPRvlWE+uU/Av2dVOlvp1bqAx0NDaolU6JzqHuDpgxQgo0m38On1CkLkJjUs+fOow1lvT8NK7gUNI1R5XBKO+U/wq+XTSiJPINpUHquG86BOaTzQ8Gzp6NIJYe3jb5LpPB/DxAuoQt8/f5caQoVyfORLKM3E/vHJ9j+OnXWDym1hC1f06ZPH9mwy7WnBoXZZWoGc6sZeNhghxnPvZibpBIAFvXZfzW9UI+pfEXMvadV/QiV22WsPVPj7l4+bK5zrfKLjDRqG681lUwllXYwwZ0i85QqMqSRXofzPPYjbCaDL9X+8qFcBr3lxi7wUYQtGUbSNd2aNZHfgKVO5E6cxUkpjP0dU1tt7KMibP0hduYXnBY1YOcO3+WxmlV1LHM1cS07S6e2Zo25oyRRiMkGlWSDPoI/ZrnWfXlN+v6Plv0cBeBAXlMt+sWcR7HfRALUxHpVLJ1nNjNmx27ns1/ggnaGqlj/GpAJFXvojHMBWB/92yFNvTPsqhINGbsySw4K9l91Su1RN/K+MfPr3EvLmyH31P/vLDzpn0asQW6G94JjkszDW1oVOMzFqNG9MPnlzUDP41n1FUATTVLoCJ86eeC7BoK6nqLClfDiE2hWJeVuXxVFRrTA9tSAEiGqYDIH0pbZ8BBhhzZrJjEqhQ=

language: node_js
node_js: 4
branches:
  only:
    - master
script:
  - npm run doc
after_success:
  - ./deploy.sh

cache:
  directories: 
    - node_modules
